version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      javascript-dependencies:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: monthly
    groups:
      android-tooling:
        patterns: ["*"]
